sudo: false
language: python
python:
  - 3.7
  - 3.8
  - 3.9
cache:
  pip: true

before_install:
 - pip install poetry

install:
  - poetry install
script:
- poetry run flake8 amqtt_db test
- poetry run coverage run --source=amqtt_db -m unittest discover -b

notifications:
  email:
    - volker.jaenisch@inqbus.de
