[tool.poetry]
name = "amqtt_db"
version = "0.1.0"
description = ""
authors = ["volker <volker.jaenisch@inqbus.de>"]

[tool.poetry.dependencies]
python = "^3.7"
amqtt = "^0.10.0-alpha.1"
SQLAlchemy = "^1.4.1"
aiounittest = "^1.4.0"
psycopg2 = "^2.8.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.plugins."hbmqtt.broker.plugins"]
amqtt_db = "amqtt_db.plugin:DBPlugin"